---
- name: Gather Facts then Sleep via CLI
  hosts: all
  gather_facts: true
  
  vars:
    sleep_time: 1
    termination_wait: 120
   
  tasks:
    - name: "Sleep {{ sleep_time }}"
      ansible.builtin.command: sleep "{{ sleep_time }}"

    - name: Outout after sleep
      ansible.builtin.debug:
        msg: "Sleep {{ sleep_time }} completed."

    - name: Output facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Set Facts
      ansible.builtin.set_fact:
        more_data: "{{ ansible_facts }}"
        delegate_facts: true

    - name: "Delay Playbook Termination by {{ termination_wait }}"
      ansible.builtin.pause:
        seconds: "{{ termination_wait }}"
